<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class EventExhibitorsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('event_exhibitors')->delete();
        
        \DB::table('event_exhibitors')->insert(array (
            0 => 
            array (
                'id' => 1,
                'code' => 'EX-072026-0001',
                'title' => 'STARBOOKS',
                'institution' => 'DOST - Science and Technology Information Institute Library',
                'description' => 'STARBOOKS',
                'area' => NULL,
                'is_active' => 1,
                'type_id' => 74,
                'event_id' => 1,
                'created_at' => '2026-07-21 13:54:46',
                'updated_at' => '2026-07-21 13:54:46',
            ),
            1 => 
            array (
                'id' => 2,
                'code' => 'EX-072026-0002',
                'title' => '21st CLEM, Robotics, Interactive exhibit',
                'institution' => 'Philippine Science High School - Zamboanga Peninsula Region Campus',
                'description' => '21st CLEM, Robotics, Interactive exhibit',
                'area' => NULL,
                'is_active' => 1,
                'type_id' => 74,
                'event_id' => 1,
                'created_at' => '2026-07-21 13:55:12',
                'updated_at' => '2026-07-21 13:55:12',
            ),
            2 => 
            array (
                'id' => 3,
                'code' => 'EX-072026-0003',
                'title' => 'WELA School Systems',
                'institution' => 'Wela Online Corp',
                'description' => 'WELA School Systems',
                'area' => NULL,
                'is_active' => 1,
                'type_id' => 74,
                'event_id' => 1,
                'created_at' => '2026-07-21 13:56:25',
                'updated_at' => '2026-07-21 13:56:25',
            ),
            3 => 
            array (
                'id' => 4,
                'code' => 'EX-072026-0004',
            'title' => 'Science Centrum (Offsite)',
                'institution' => 'Department of Education Dipolog',
            'description' => 'Science Centrum (Offsite)',
                'area' => NULL,
                'is_active' => 1,
                'type_id' => 75,
                'event_id' => 1,
                'created_at' => '2026-07-21 13:57:20',
                'updated_at' => '2026-07-21 13:57:20',
            ),
            4 => 
            array (
                'id' => 5,
                'code' => 'EX-072026-0005',
                'title' => 'Planetarium',
                'institution' => 'Department of Science and Technology - Philippine Atmospheric, Geophysical and Astronomical Services Administration',
                'description' => 'Planetarium',
                'area' => NULL,
                'is_active' => 1,
                'type_id' => 74,
                'event_id' => 1,
                'created_at' => '2026-07-21 13:58:06',
                'updated_at' => '2026-07-21 13:58:06',
            ),
            5 => 
            array (
                'id' => 6,
                'code' => 'EX-072026-0006',
                'title' => 'Food and Nutrition Research Institute Department of Science and Technology',
                'institution' => 'Food and Nutrition Research Institute Department of Science and Technology',
                'description' => 'Food and Nutrition Research Institute Department of Science and Technology',
                'area' => NULL,
                'is_active' => 1,
                'type_id' => 74,
                'event_id' => 1,
                'created_at' => '2026-07-21 13:58:48',
                'updated_at' => '2026-07-21 13:58:48',
            ),
            6 => 
            array (
                'id' => 7,
                'code' => 'EX-072026-0007',
                'title' => 'REIINN LokalFi and RCAst',
                'institution' => 'Deparment of Science and Technology - Advanced Science and Technology Institute',
                'description' => 'REIINN LokalFi and RCAst',
                'area' => NULL,
                'is_active' => 1,
                'type_id' => 74,
                'event_id' => 1,
                'created_at' => '2026-07-21 13:59:26',
                'updated_at' => '2026-07-21 13:59:26',
            ),
            7 => 
            array (
                'id' => 8,
                'code' => 'EX-072026-0008',
                'title' => 'Pack of Hope: RTE',
                'institution' => 'Department of Science and Technology Industrial Technology Development Institute',
                'description' => 'Pack of Hope: RTE',
                'area' => NULL,
                'is_active' => 1,
                'type_id' => 74,
                'event_id' => 1,
                'created_at' => '2026-07-21 14:00:00',
                'updated_at' => '2026-07-21 14:00:00',
            ),
            8 => 
            array (
                'id' => 9,
                'code' => 'EX-072026-0009',
                'title' => 'Coco Dehusker, Zampen Native Chicken',
                'institution' => 'Coco Dehusker, Zampen Native Chicken',
                'description' => 'Coco Dehusker, Zampen Native Chicken',
                'area' => NULL,
                'is_active' => 1,
                'type_id' => 72,
                'event_id' => 1,
                'created_at' => '2026-07-21 14:00:27',
                'updated_at' => '2026-07-21 14:00:27',
            ),
            9 => 
            array (
                'id' => 10,
                'code' => 'EX-072026-0010',
                'title' => 'AZUL Hub',
                'institution' => 'Ateneo de Zamboanga University',
                'description' => 'AZUL Hub',
                'area' => NULL,
                'is_active' => 1,
                'type_id' => 72,
                'event_id' => 1,
                'created_at' => '2026-07-21 14:00:54',
                'updated_at' => '2026-07-21 14:00:54',
            ),
            10 => 
            array (
                'id' => 11,
                'code' => 'EX-072026-0011',
                'title' => 'SIDLAK TBI',
                'institution' => 'Jose Rizal Memorial State University',
                'description' => 'SIDLAK TBI',
                'area' => NULL,
                'is_active' => 1,
                'type_id' => 72,
                'event_id' => 1,
                'created_at' => '2026-07-21 14:01:23',
                'updated_at' => '2026-07-21 14:01:23',
            ),
            11 => 
            array (
                'id' => 12,
                'code' => 'EX-072026-0012',
                'title' => 'Agri-Aqua Technology Business Incubator',
                'institution' => 'Western Mindanao State University',
                'description' => 'Agri-Aqua Technology Business Incubator',
                'area' => NULL,
                'is_active' => 1,
                'type_id' => 72,
                'event_id' => 1,
                'created_at' => '2026-07-21 14:02:49',
                'updated_at' => '2026-07-21 14:02:49',
            ),
            12 => 
            array (
                'id' => 13,
                'code' => 'EX-072026-0013',
            'title' => 'Engineered Bamboo Technologies, Bamboo Musical Instrument (BMI)',
                'institution' => 'Department of Science and Technology - Forest Products Research and Development Institute',
            'description' => 'Engineered Bamboo Technologies, Bamboo Musical Instrument (BMI)',
                'area' => NULL,
                'is_active' => 1,
                'type_id' => 72,
                'event_id' => 1,
                'created_at' => '2026-07-21 14:03:24',
                'updated_at' => '2026-07-21 14:03:24',
            ),
            13 => 
            array (
                'id' => 14,
                'code' => 'EX-072026-0014',
                'title' => 'Regional Handloom Weaving Innovation Hubs',
                'institution' => 'Department of Science and Technology - Philippine Textile Research Institute',
                'description' => 'Regional Handloom Weaving Innovation Hubs',
                'area' => NULL,
                'is_active' => 1,
                'type_id' => 72,
                'event_id' => 1,
                'created_at' => '2026-07-21 14:04:08',
                'updated_at' => '2026-07-21 14:04:08',
            ),
            14 => 
            array (
                'id' => 15,
                'code' => 'EX-072026-0015',
                'title' => 'NatDyes',
                'institution' => 'Department of Science and Technology - Philippine Textile Research Institute',
                'description' => 'NatDyes',
                'area' => NULL,
                'is_active' => 1,
                'type_id' => 72,
                'event_id' => 1,
                'created_at' => '2026-07-21 14:04:35',
                'updated_at' => '2026-07-21 14:04:35',
            ),
            15 => 
            array (
                'id' => 16,
                'code' => 'EX-072026-0016',
                'title' => 'SAFATOS Program',
                'institution' => 'Department of Science and Technology - Philippine Textile Research Institute',
                'description' => 'SAFATOS Program',
                'area' => NULL,
                'is_active' => 1,
                'type_id' => 72,
                'event_id' => 1,
                'created_at' => '2026-07-21 14:04:47',
                'updated_at' => '2026-07-21 14:04:47',
            ),
            16 => 
            array (
                'id' => 17,
                'code' => 'EX-072026-0017',
                'title' => 'Food Innovation Centers Technology',
                'institution' => 'Food Innovation Centers',
                'description' => 'Food Innovation Centers Technology',
                'area' => NULL,
                'is_active' => 1,
                'type_id' => 72,
                'event_id' => 1,
                'created_at' => '2026-07-21 14:05:44',
                'updated_at' => '2026-07-21 14:05:44',
            ),
            17 => 
            array (
                'id' => 18,
                'code' => 'EX-072026-0018',
                'title' => 'Metals and Engineering Innovation Center',
                'institution' => 'Zamboanga Peninsula Polytechnic State University',
                'description' => 'Metals and Engineering Innovation Center',
                'area' => NULL,
                'is_active' => 1,
                'type_id' => 72,
                'event_id' => 1,
                'created_at' => '2026-07-21 14:06:09',
                'updated_at' => '2026-07-21 14:06:09',
            ),
            18 => 
            array (
                'id' => 19,
                'code' => 'EX-072026-0019',
                'title' => 'Advanced Manufacturing Center',
                'institution' => 'Western Mindanao State University',
                'description' => 'Advanced Manufacturing Center',
                'area' => NULL,
                'is_active' => 1,
                'type_id' => 72,
                'event_id' => 1,
                'created_at' => '2026-07-21 14:06:41',
                'updated_at' => '2026-07-21 14:06:41',
            ),
            19 => 
            array (
                'id' => 20,
                'code' => 'EX-072026-0020',
                'title' => 'DOST-IX Regional Standards and Testing Laboratories Booth',
                'institution' => 'Department of Science and Technology Region IX',
                'description' => 'DOST-IX Regional Standards and Testing Laboratories Booth',
                'area' => NULL,
                'is_active' => 1,
                'type_id' => 72,
                'event_id' => 1,
                'created_at' => '2026-07-21 14:07:27',
                'updated_at' => '2026-07-21 14:07:27',
            ),
            20 => 
            array (
                'id' => 21,
                'code' => 'EX-072026-0021',
                'title' => 'Philippine Council for Agriculture, Aquatic and Natural Resources Research and Development',
                'institution' => 'Department of Science and Technology - The Philippine Council for Agriculture, Aquatic and Natural Resources Research and Development',
                'description' => 'The Philippine Council for Agriculture, Aquatic and Natural Resources Research and Development',
                'area' => NULL,
                'is_active' => 1,
                'type_id' => 72,
                'event_id' => 1,
                'created_at' => '2026-07-21 14:08:02',
                'updated_at' => '2026-07-21 14:08:02',
            ),
            21 => 
            array (
                'id' => 22,
                'code' => 'EX-072026-0022',
                'title' => 'Automated Water-Level and Rain Monitoring Using Near-Real Time Observation',
                'institution' => 'Ateneo de Zamboanga University',
                'description' => 'Automated Water-Level and Rain Monitoring Using Near-Real Time Observation',
                'area' => NULL,
                'is_active' => 1,
                'type_id' => 75,
                'event_id' => 1,
                'created_at' => '2026-07-21 14:10:06',
                'updated_at' => '2026-07-21 14:10:06',
            ),
            22 => 
            array (
                'id' => 23,
                'code' => 'EX-072026-0023',
                'title' => 'Autonomous Societally Inspired Mission Oriented Vehicles - Harmonized Aerial Watch and Knowledge-Based Survey',
                'institution' => 'Department of Science and Technology - Advanced Science and Technology Institute',
                'description' => 'Autonomous Societally Inspired Mission Oriented Vehicles - Harmonized Aerial Watch and Knowledge-Based Survey',
                'area' => NULL,
                'is_active' => 1,
                'type_id' => 75,
                'event_id' => 1,
                'created_at' => '2026-07-21 14:10:55',
                'updated_at' => '2026-07-21 14:10:55',
            ),
            23 => 
            array (
                'id' => 24,
                'code' => 'EX-072026-0024',
                'title' => 'Automated Rain Gauge',
                'institution' => 'Department of Science and Technology - Advanced Science and Technology Institute',
                'description' => 'Automated Rain Gauge',
                'area' => NULL,
                'is_active' => 1,
                'type_id' => 75,
                'event_id' => 1,
                'created_at' => '2026-07-21 14:11:29',
                'updated_at' => '2026-07-21 14:11:29',
            ),
            24 => 
            array (
                'id' => 25,
                'code' => 'EX-072026-0025',
                'title' => 'Waterlevel Monitoring System',
                'institution' => 'Department of Science and Technology - Advanced Science and Technology Institute',
                'description' => 'Waterlevel Monitoring System',
                'area' => NULL,
                'is_active' => 1,
                'type_id' => 75,
                'event_id' => 1,
                'created_at' => '2026-07-21 14:12:21',
                'updated_at' => '2026-07-21 14:12:21',
            ),
            25 => 
            array (
                'id' => 26,
                'code' => 'EX-072026-0026',
                'title' => 'Water Rain Monitoring System',
                'institution' => 'Department of Science and Technology - Advanced Science and Technology Institute',
                'description' => 'Water Rain Monitoring System',
                'area' => NULL,
                'is_active' => 1,
                'type_id' => 75,
                'event_id' => 1,
                'created_at' => '2026-07-21 14:13:55',
                'updated_at' => '2026-07-21 14:13:55',
            ),
            26 => 
            array (
                'id' => 27,
                'code' => 'EX-072026-0027',
                'title' => 'GeoRisk',
                'institution' => 'Deparment of Science and Technology - Philippine Institute of Volcanology and Seismology',
                'description' => 'GeoRisk',
                'area' => NULL,
                'is_active' => 1,
                'type_id' => 75,
                'event_id' => 1,
                'created_at' => '2026-07-21 14:15:42',
                'updated_at' => '2026-07-21 14:15:42',
            ),
            27 => 
            array (
                'id' => 28,
                'code' => 'EX-072026-0028',
                'title' => 'Rapid Earthquake Damage Assessment System',
                'institution' => 'Deparment of Science and Technology - Philippine Institute of Volcanology and Seismology',
                'description' => 'Rapid Earthquake Damage Assessment System',
                'area' => NULL,
                'is_active' => 1,
                'type_id' => 75,
                'event_id' => 1,
                'created_at' => '2026-07-21 14:16:00',
                'updated_at' => '2026-07-21 14:16:00',
            ),
            28 => 
            array (
                'id' => 29,
                'code' => 'EX-072026-0029',
                'title' => 'Earthquake Simulator',
                'institution' => 'Deparment of Science and Technology - Philippine Institute of Volcanology and Seismology',
                'description' => 'Earthquake Simulator',
                'area' => NULL,
                'is_active' => 1,
                'type_id' => 75,
                'event_id' => 1,
                'created_at' => '2026-07-21 14:16:16',
                'updated_at' => '2026-07-21 14:16:16',
            ),
            29 => 
            array (
                'id' => 30,
                'code' => 'EX-072026-0030',
                'title' => 'Handa Integrated Platform',
                'institution' => 'Deparment of Science and Technology - Philippine Institute of Volcanology and Seismology',
                'description' => 'Handa Integrated Platform',
                'area' => NULL,
                'is_active' => 1,
                'type_id' => 75,
                'event_id' => 1,
                'created_at' => '2026-07-21 14:16:32',
                'updated_at' => '2026-07-21 14:16:32',
            ),
            30 => 
            array (
                'id' => 31,
                'code' => 'EX-072026-0031',
            'title' => 'E-mobility (C-Trike, e-Trike, e-Tram)',
                'institution' => 'Cagayan State University',
            'description' => 'E-mobility (C-Trike, e-Trike, e-Tram)',
                'area' => NULL,
                'is_active' => 1,
                'type_id' => 73,
                'event_id' => 1,
                'created_at' => '2026-07-21 14:16:45',
                'updated_at' => '2026-07-21 14:16:45',
            ),
            31 => 
            array (
                'id' => 32,
                'code' => 'EX-072026-0032',
                'title' => 'Smarter Approaches to Reinvigorate Agriculture as an Industry',
                'institution' => 'SARAi & University of the Philippines Los Baños',
            'description' => 'Smarter Approaches to Reinvigorate Agriculture as an Industry)',
            'area' => NULL,
            'is_active' => 1,
            'type_id' => 73,
            'event_id' => 1,
            'created_at' => '2026-07-21 14:17:35',
            'updated_at' => '2026-07-21 14:17:35',
        ),
        32 => 
        array (
            'id' => 33,
            'code' => 'EX-072026-0033',
            'title' => 'Charging in Minutes',
            'institution' => 'CHRG EV Technologies Inc..',
            'description' => 'Charging in Minutes',
            'area' => NULL,
            'is_active' => 1,
            'type_id' => 73,
            'event_id' => 1,
            'created_at' => '2026-07-21 14:18:05',
            'updated_at' => '2026-07-21 14:18:05',
        ),
        33 => 
        array (
            'id' => 34,
            'code' => 'EX-072026-0034',
            'title' => 'Department of Science and Technology - Freedom of Information',
            'institution' => 'Department of Science and Technology - Freedom of Information',
            'description' => 'Department of Science and Technology - Freedom of Information',
            'area' => NULL,
            'is_active' => 1,
            'type_id' => 73,
            'event_id' => 1,
            'created_at' => '2026-07-21 14:18:33',
            'updated_at' => '2026-07-21 14:18:33',
        ),
        34 => 
        array (
            'id' => 35,
            'code' => 'EX-072026-0035',
            'title' => 'Gender and Development',
            'institution' => 'Department of Science and Technology Region IX',
            'description' => 'Gender and Development',
            'area' => NULL,
            'is_active' => 1,
            'type_id' => 73,
            'event_id' => 1,
            'created_at' => '2026-07-21 14:18:56',
            'updated_at' => '2026-07-21 14:18:56',
        ),
    ));
        
        
    }
}