<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UserRolesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('user_roles')->delete();
        
        \DB::table('user_roles')->insert(array (
            0 => 
            array (
                'id' => 1,
                'is_active' => 1,
                'user_id' => 1,
                'role_id' => 1,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-12 07:56:20',
                'updated_at' => '2026-01-12 07:56:20',
            ),
            1 => 
            array (
                'id' => 2,
                'is_active' => 1,
                'user_id' => 1,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-12 07:56:20',
                'updated_at' => '2026-01-12 07:56:20',
            ),
            2 => 
            array (
                'id' => 3,
                'is_active' => 1,
                'user_id' => 1,
                'role_id' => 4,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-12 07:59:14',
                'updated_at' => '2026-01-12 07:59:14',
            ),
            3 => 
            array (
                'id' => 4,
                'is_active' => 1,
                'user_id' => 2,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-12 10:43:13',
                'updated_at' => '2026-01-12 10:43:13',
            ),
            4 => 
            array (
                'id' => 5,
                'is_active' => 1,
                'user_id' => 3,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-12 10:44:00',
                'updated_at' => '2026-01-12 10:44:00',
            ),
            5 => 
            array (
                'id' => 6,
                'is_active' => 1,
                'user_id' => 4,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-12 10:44:49',
                'updated_at' => '2026-01-12 10:44:49',
            ),
            6 => 
            array (
                'id' => 7,
                'is_active' => 1,
                'user_id' => 5,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-12 10:45:31',
                'updated_at' => '2026-01-12 10:45:31',
            ),
            7 => 
            array (
                'id' => 8,
                'is_active' => 1,
                'user_id' => 6,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-12 10:46:06',
                'updated_at' => '2026-01-12 10:46:06',
            ),
            8 => 
            array (
                'id' => 9,
                'is_active' => 1,
                'user_id' => 7,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-12 10:46:52',
                'updated_at' => '2026-01-12 10:46:52',
            ),
            9 => 
            array (
                'id' => 10,
                'is_active' => 1,
                'user_id' => 8,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-12 15:40:03',
                'updated_at' => '2026-01-12 15:40:03',
            ),
            10 => 
            array (
                'id' => 11,
                'is_active' => 1,
                'user_id' => 9,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-12 15:41:42',
                'updated_at' => '2026-01-12 15:41:42',
            ),
            11 => 
            array (
                'id' => 12,
                'is_active' => 1,
                'user_id' => 10,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-12 15:42:52',
                'updated_at' => '2026-01-12 15:42:52',
            ),
            12 => 
            array (
                'id' => 13,
                'is_active' => 1,
                'user_id' => 11,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-12 15:44:09',
                'updated_at' => '2026-01-12 15:44:09',
            ),
            13 => 
            array (
                'id' => 14,
                'is_active' => 1,
                'user_id' => 12,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-12 15:45:17',
                'updated_at' => '2026-01-12 15:45:17',
            ),
            14 => 
            array (
                'id' => 15,
                'is_active' => 1,
                'user_id' => 13,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-12 15:46:28',
                'updated_at' => '2026-01-12 15:46:28',
            ),
            15 => 
            array (
                'id' => 16,
                'is_active' => 1,
                'user_id' => 14,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-12 15:47:57',
                'updated_at' => '2026-01-12 15:47:57',
            ),
            16 => 
            array (
                'id' => 17,
                'is_active' => 1,
                'user_id' => 15,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-12 15:49:33',
                'updated_at' => '2026-01-12 15:49:33',
            ),
            17 => 
            array (
                'id' => 18,
                'is_active' => 1,
                'user_id' => 16,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-12 15:50:45',
                'updated_at' => '2026-01-12 15:50:45',
            ),
            18 => 
            array (
                'id' => 19,
                'is_active' => 1,
                'user_id' => 17,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-12 15:51:38',
                'updated_at' => '2026-01-12 15:51:38',
            ),
            19 => 
            array (
                'id' => 20,
                'is_active' => 1,
                'user_id' => 18,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-12 15:57:33',
                'updated_at' => '2026-01-12 15:57:33',
            ),
            20 => 
            array (
                'id' => 21,
                'is_active' => 1,
                'user_id' => 19,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-12 22:46:47',
                'updated_at' => '2026-01-12 22:46:47',
            ),
            21 => 
            array (
                'id' => 22,
                'is_active' => 1,
                'user_id' => 20,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-12 22:49:02',
                'updated_at' => '2026-01-12 22:49:02',
            ),
            22 => 
            array (
                'id' => 23,
                'is_active' => 1,
                'user_id' => 21,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-12 22:50:38',
                'updated_at' => '2026-01-12 22:50:38',
            ),
            23 => 
            array (
                'id' => 24,
                'is_active' => 1,
                'user_id' => 22,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-12 22:52:03',
                'updated_at' => '2026-01-12 22:52:03',
            ),
            24 => 
            array (
                'id' => 25,
                'is_active' => 1,
                'user_id' => 23,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-12 22:53:39',
                'updated_at' => '2026-01-12 22:53:39',
            ),
            25 => 
            array (
                'id' => 26,
                'is_active' => 1,
                'user_id' => 24,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-12 22:55:07',
                'updated_at' => '2026-01-12 22:55:07',
            ),
            26 => 
            array (
                'id' => 27,
                'is_active' => 1,
                'user_id' => 25,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-12 22:56:53',
                'updated_at' => '2026-01-12 22:56:53',
            ),
            27 => 
            array (
                'id' => 28,
                'is_active' => 1,
                'user_id' => 26,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-12 22:58:52',
                'updated_at' => '2026-01-12 22:58:52',
            ),
            28 => 
            array (
                'id' => 29,
                'is_active' => 1,
                'user_id' => 27,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-12 23:00:09',
                'updated_at' => '2026-01-12 23:00:09',
            ),
            29 => 
            array (
                'id' => 30,
                'is_active' => 1,
                'user_id' => 28,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-14 09:28:53',
                'updated_at' => '2026-01-14 09:28:53',
            ),
            30 => 
            array (
                'id' => 31,
                'is_active' => 1,
                'user_id' => 29,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-14 09:37:28',
                'updated_at' => '2026-01-14 09:37:28',
            ),
            31 => 
            array (
                'id' => 32,
                'is_active' => 1,
                'user_id' => 30,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-14 09:39:32',
                'updated_at' => '2026-01-14 09:39:32',
            ),
            32 => 
            array (
                'id' => 33,
                'is_active' => 1,
                'user_id' => 31,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-14 10:13:26',
                'updated_at' => '2026-01-14 10:13:26',
            ),
            33 => 
            array (
                'id' => 34,
                'is_active' => 1,
                'user_id' => 32,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-14 10:14:47',
                'updated_at' => '2026-01-14 10:14:47',
            ),
            34 => 
            array (
                'id' => 35,
                'is_active' => 1,
                'user_id' => 33,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-14 13:20:54',
                'updated_at' => '2026-01-14 13:20:54',
            ),
            35 => 
            array (
                'id' => 36,
                'is_active' => 1,
                'user_id' => 34,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-14 13:21:51',
                'updated_at' => '2026-01-14 13:21:51',
            ),
            36 => 
            array (
                'id' => 37,
                'is_active' => 1,
                'user_id' => 35,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-14 13:24:47',
                'updated_at' => '2026-01-14 13:24:47',
            ),
            37 => 
            array (
                'id' => 38,
                'is_active' => 1,
                'user_id' => 36,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-14 13:26:00',
                'updated_at' => '2026-01-14 13:26:00',
            ),
            38 => 
            array (
                'id' => 39,
                'is_active' => 1,
                'user_id' => 37,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-14 13:27:04',
                'updated_at' => '2026-01-14 13:27:04',
            ),
            39 => 
            array (
                'id' => 40,
                'is_active' => 1,
                'user_id' => 38,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-14 13:28:41',
                'updated_at' => '2026-01-14 13:28:41',
            ),
            40 => 
            array (
                'id' => 41,
                'is_active' => 1,
                'user_id' => 39,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-19 13:36:36',
                'updated_at' => '2026-01-19 13:36:36',
            ),
            41 => 
            array (
                'id' => 42,
                'is_active' => 1,
                'user_id' => 40,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-19 13:40:35',
                'updated_at' => '2026-01-19 13:40:35',
            ),
            42 => 
            array (
                'id' => 43,
                'is_active' => 1,
                'user_id' => 41,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-19 13:44:53',
                'updated_at' => '2026-01-19 13:44:53',
            ),
            43 => 
            array (
                'id' => 44,
                'is_active' => 1,
                'user_id' => 42,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-19 13:46:46',
                'updated_at' => '2026-01-19 13:46:46',
            ),
            44 => 
            array (
                'id' => 45,
                'is_active' => 1,
                'user_id' => 43,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-19 13:55:52',
                'updated_at' => '2026-01-19 13:55:52',
            ),
            45 => 
            array (
                'id' => 46,
                'is_active' => 1,
                'user_id' => 44,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-19 14:00:04',
                'updated_at' => '2026-01-19 14:00:04',
            ),
            46 => 
            array (
                'id' => 47,
                'is_active' => 1,
                'user_id' => 45,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-19 14:03:44',
                'updated_at' => '2026-01-19 14:03:44',
            ),
            47 => 
            array (
                'id' => 48,
                'is_active' => 1,
                'user_id' => 46,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-19 14:05:25',
                'updated_at' => '2026-01-19 14:05:25',
            ),
            48 => 
            array (
                'id' => 49,
                'is_active' => 1,
                'user_id' => 47,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-19 14:09:13',
                'updated_at' => '2026-01-19 14:09:13',
            ),
            49 => 
            array (
                'id' => 50,
                'is_active' => 1,
                'user_id' => 48,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-19 14:11:43',
                'updated_at' => '2026-01-19 14:11:43',
            ),
            50 => 
            array (
                'id' => 51,
                'is_active' => 1,
                'user_id' => 49,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-19 14:16:27',
                'updated_at' => '2026-01-19 14:16:27',
            ),
            51 => 
            array (
                'id' => 52,
                'is_active' => 1,
                'user_id' => 50,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-19 14:20:42',
                'updated_at' => '2026-01-19 14:20:42',
            ),
            52 => 
            array (
                'id' => 53,
                'is_active' => 1,
                'user_id' => 51,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-19 14:28:19',
                'updated_at' => '2026-01-19 14:28:19',
            ),
            53 => 
            array (
                'id' => 54,
                'is_active' => 1,
                'user_id' => 52,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-19 14:31:54',
                'updated_at' => '2026-01-19 14:31:54',
            ),
            54 => 
            array (
                'id' => 55,
                'is_active' => 1,
                'user_id' => 53,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-19 14:34:49',
                'updated_at' => '2026-01-19 14:34:49',
            ),
            55 => 
            array (
                'id' => 56,
                'is_active' => 1,
                'user_id' => 54,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-19 14:36:53',
                'updated_at' => '2026-01-19 14:36:53',
            ),
            56 => 
            array (
                'id' => 57,
                'is_active' => 1,
                'user_id' => 55,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-19 14:39:48',
                'updated_at' => '2026-01-19 14:39:48',
            ),
            57 => 
            array (
                'id' => 58,
                'is_active' => 1,
                'user_id' => 56,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-19 14:57:22',
                'updated_at' => '2026-01-19 14:57:22',
            ),
            58 => 
            array (
                'id' => 59,
                'is_active' => 1,
                'user_id' => 57,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-19 15:06:53',
                'updated_at' => '2026-01-19 15:06:53',
            ),
            59 => 
            array (
                'id' => 60,
                'is_active' => 1,
                'user_id' => 58,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-19 16:16:39',
                'updated_at' => '2026-01-19 16:16:39',
            ),
            60 => 
            array (
                'id' => 61,
                'is_active' => 1,
                'user_id' => 59,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-19 16:21:57',
                'updated_at' => '2026-01-19 16:21:57',
            ),
            61 => 
            array (
                'id' => 62,
                'is_active' => 1,
                'user_id' => 60,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-20 13:31:02',
                'updated_at' => '2026-01-20 13:31:02',
            ),
            62 => 
            array (
                'id' => 63,
                'is_active' => 1,
                'user_id' => 61,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-20 13:34:26',
                'updated_at' => '2026-01-20 13:34:26',
            ),
            63 => 
            array (
                'id' => 64,
                'is_active' => 1,
                'user_id' => 62,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-20 13:37:33',
                'updated_at' => '2026-01-20 13:37:33',
            ),
            64 => 
            array (
                'id' => 65,
                'is_active' => 1,
                'user_id' => 63,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-20 13:43:52',
                'updated_at' => '2026-01-20 13:43:52',
            ),
            65 => 
            array (
                'id' => 66,
                'is_active' => 1,
                'user_id' => 64,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-20 13:49:12',
                'updated_at' => '2026-01-20 13:49:12',
            ),
            66 => 
            array (
                'id' => 67,
                'is_active' => 1,
                'user_id' => 65,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-20 13:50:37',
                'updated_at' => '2026-01-20 13:50:37',
            ),
            67 => 
            array (
                'id' => 68,
                'is_active' => 1,
                'user_id' => 67,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-20 15:32:09',
                'updated_at' => '2026-01-20 15:32:09',
            ),
            68 => 
            array (
                'id' => 69,
                'is_active' => 1,
                'user_id' => 68,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-20 15:42:32',
                'updated_at' => '2026-01-20 15:42:32',
            ),
            69 => 
            array (
                'id' => 70,
                'is_active' => 1,
                'user_id' => 69,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-20 15:55:05',
                'updated_at' => '2026-01-20 15:55:05',
            ),
            70 => 
            array (
                'id' => 71,
                'is_active' => 1,
                'user_id' => 70,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-20 15:57:45',
                'updated_at' => '2026-01-20 15:57:45',
            ),
            71 => 
            array (
                'id' => 72,
                'is_active' => 1,
                'user_id' => 71,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-20 16:06:26',
                'updated_at' => '2026-01-20 16:06:26',
            ),
            72 => 
            array (
                'id' => 73,
                'is_active' => 1,
                'user_id' => 72,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-20 16:12:04',
                'updated_at' => '2026-01-20 16:12:04',
            ),
            73 => 
            array (
                'id' => 74,
                'is_active' => 1,
                'user_id' => 73,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-20 16:13:50',
                'updated_at' => '2026-01-20 16:13:50',
            ),
            74 => 
            array (
                'id' => 75,
                'is_active' => 1,
                'user_id' => 74,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-21 08:15:01',
                'updated_at' => '2026-01-21 08:15:01',
            ),
            75 => 
            array (
                'id' => 76,
                'is_active' => 1,
                'user_id' => 75,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-21 08:17:21',
                'updated_at' => '2026-01-21 08:17:21',
            ),
            76 => 
            array (
                'id' => 77,
                'is_active' => 1,
                'user_id' => 76,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-21 08:21:39',
                'updated_at' => '2026-01-21 08:21:39',
            ),
            77 => 
            array (
                'id' => 78,
                'is_active' => 1,
                'user_id' => 77,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-21 08:24:35',
                'updated_at' => '2026-01-21 08:24:35',
            ),
            78 => 
            array (
                'id' => 79,
                'is_active' => 1,
                'user_id' => 78,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-21 08:27:49',
                'updated_at' => '2026-01-21 08:27:49',
            ),
            79 => 
            array (
                'id' => 80,
                'is_active' => 1,
                'user_id' => 79,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-21 08:33:04',
                'updated_at' => '2026-01-21 08:33:04',
            ),
            80 => 
            array (
                'id' => 81,
                'is_active' => 1,
                'user_id' => 80,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-21 08:34:59',
                'updated_at' => '2026-01-21 08:34:59',
            ),
            81 => 
            array (
                'id' => 82,
                'is_active' => 1,
                'user_id' => 81,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-21 08:37:29',
                'updated_at' => '2026-01-21 08:37:29',
            ),
            82 => 
            array (
                'id' => 83,
                'is_active' => 1,
                'user_id' => 82,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-21 08:41:40',
                'updated_at' => '2026-01-21 08:41:40',
            ),
            83 => 
            array (
                'id' => 84,
                'is_active' => 1,
                'user_id' => 83,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-21 08:44:50',
                'updated_at' => '2026-01-21 08:44:50',
            ),
            84 => 
            array (
                'id' => 85,
                'is_active' => 1,
                'user_id' => 84,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-21 08:48:34',
                'updated_at' => '2026-01-21 08:48:34',
            ),
            85 => 
            array (
                'id' => 86,
                'is_active' => 1,
                'user_id' => 85,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-21 08:52:47',
                'updated_at' => '2026-01-21 08:52:47',
            ),
            86 => 
            array (
                'id' => 87,
                'is_active' => 1,
                'user_id' => 86,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-21 09:07:48',
                'updated_at' => '2026-01-21 09:07:48',
            ),
            87 => 
            array (
                'id' => 88,
                'is_active' => 1,
                'user_id' => 87,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-21 09:14:17',
                'updated_at' => '2026-01-21 09:14:17',
            ),
            88 => 
            array (
                'id' => 89,
                'is_active' => 1,
                'user_id' => 88,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-21 09:22:04',
                'updated_at' => '2026-01-21 09:22:04',
            ),
            89 => 
            array (
                'id' => 90,
                'is_active' => 1,
                'user_id' => 89,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-21 09:29:23',
                'updated_at' => '2026-01-21 09:29:23',
            ),
            90 => 
            array (
                'id' => 91,
                'is_active' => 1,
                'user_id' => 90,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-21 09:34:09',
                'updated_at' => '2026-01-21 09:34:09',
            ),
            91 => 
            array (
                'id' => 92,
                'is_active' => 1,
                'user_id' => 91,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-21 09:39:10',
                'updated_at' => '2026-01-21 09:39:10',
            ),
            92 => 
            array (
                'id' => 93,
                'is_active' => 1,
                'user_id' => 92,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-21 09:58:20',
                'updated_at' => '2026-01-21 09:58:20',
            ),
            93 => 
            array (
                'id' => 94,
                'is_active' => 1,
                'user_id' => 93,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-21 10:08:11',
                'updated_at' => '2026-01-21 10:08:11',
            ),
            94 => 
            array (
                'id' => 95,
                'is_active' => 1,
                'user_id' => 94,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-21 10:12:21',
                'updated_at' => '2026-01-21 10:12:21',
            ),
            95 => 
            array (
                'id' => 96,
                'is_active' => 1,
                'user_id' => 95,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-21 15:47:18',
                'updated_at' => '2026-01-21 15:47:18',
            ),
            96 => 
            array (
                'id' => 97,
                'is_active' => 1,
                'user_id' => 96,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-21 15:48:35',
                'updated_at' => '2026-01-21 15:48:35',
            ),
            97 => 
            array (
                'id' => 98,
                'is_active' => 1,
                'user_id' => 97,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-21 15:49:29',
                'updated_at' => '2026-01-21 15:49:29',
            ),
            98 => 
            array (
                'id' => 99,
                'is_active' => 1,
                'user_id' => 98,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-21 15:50:22',
                'updated_at' => '2026-01-21 15:50:22',
            ),
            99 => 
            array (
                'id' => 100,
                'is_active' => 1,
                'user_id' => 100,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-21 15:52:32',
                'updated_at' => '2026-01-21 15:52:32',
            ),
            100 => 
            array (
                'id' => 102,
                'is_active' => 1,
                'user_id' => 102,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-21 21:19:45',
                'updated_at' => '2026-01-21 21:19:45',
            ),
            101 => 
            array (
                'id' => 103,
                'is_active' => 1,
                'user_id' => 103,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-21 21:20:38',
                'updated_at' => '2026-01-21 21:20:38',
            ),
            102 => 
            array (
                'id' => 104,
                'is_active' => 1,
                'user_id' => 104,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-21 21:22:08',
                'updated_at' => '2026-01-21 21:22:08',
            ),
            103 => 
            array (
                'id' => 105,
                'is_active' => 1,
                'user_id' => 105,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-21 21:23:27',
                'updated_at' => '2026-01-21 21:23:27',
            ),
            104 => 
            array (
                'id' => 106,
                'is_active' => 1,
                'user_id' => 106,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-21 21:24:30',
                'updated_at' => '2026-01-21 21:24:30',
            ),
            105 => 
            array (
                'id' => 107,
                'is_active' => 1,
                'user_id' => 107,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-21 21:28:03',
                'updated_at' => '2026-01-21 21:28:03',
            ),
            106 => 
            array (
                'id' => 108,
                'is_active' => 1,
                'user_id' => 108,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-21 21:28:50',
                'updated_at' => '2026-01-21 21:28:50',
            ),
            107 => 
            array (
                'id' => 109,
                'is_active' => 1,
                'user_id' => 109,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-21 21:29:50',
                'updated_at' => '2026-01-21 21:29:50',
            ),
            108 => 
            array (
                'id' => 110,
                'is_active' => 1,
                'user_id' => 110,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-21 21:30:52',
                'updated_at' => '2026-01-21 21:30:52',
            ),
            109 => 
            array (
                'id' => 111,
                'is_active' => 1,
                'user_id' => 111,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-21 21:31:42',
                'updated_at' => '2026-01-21 21:31:42',
            ),
            110 => 
            array (
                'id' => 112,
                'is_active' => 1,
                'user_id' => 112,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-21 21:32:34',
                'updated_at' => '2026-01-21 21:32:34',
            ),
            111 => 
            array (
                'id' => 113,
                'is_active' => 1,
                'user_id' => 113,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-21 21:33:15',
                'updated_at' => '2026-01-21 21:33:15',
            ),
            112 => 
            array (
                'id' => 114,
                'is_active' => 1,
                'user_id' => 114,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-22 08:37:21',
                'updated_at' => '2026-01-22 08:37:21',
            ),
            113 => 
            array (
                'id' => 115,
                'is_active' => 1,
                'user_id' => 115,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-22 08:41:11',
                'updated_at' => '2026-01-22 08:41:11',
            ),
            114 => 
            array (
                'id' => 116,
                'is_active' => 1,
                'user_id' => 116,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-22 08:51:53',
                'updated_at' => '2026-01-22 08:51:53',
            ),
            115 => 
            array (
                'id' => 117,
                'is_active' => 1,
                'user_id' => 117,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-22 09:03:17',
                'updated_at' => '2026-01-22 09:03:17',
            ),
            116 => 
            array (
                'id' => 118,
                'is_active' => 1,
                'user_id' => 118,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-22 09:29:07',
                'updated_at' => '2026-01-22 09:29:07',
            ),
            117 => 
            array (
                'id' => 119,
                'is_active' => 1,
                'user_id' => 119,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-22 09:29:59',
                'updated_at' => '2026-01-22 09:29:59',
            ),
            118 => 
            array (
                'id' => 120,
                'is_active' => 1,
                'user_id' => 120,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-22 09:30:58',
                'updated_at' => '2026-01-22 09:30:58',
            ),
            119 => 
            array (
                'id' => 121,
                'is_active' => 1,
                'user_id' => 121,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-22 10:05:42',
                'updated_at' => '2026-01-22 10:05:42',
            ),
            120 => 
            array (
                'id' => 122,
                'is_active' => 1,
                'user_id' => 122,
                'role_id' => 2,
                'added_by' => 1,
                'removed_by' => NULL,
                'removed_at' => NULL,
                'created_at' => '2026-01-22 10:27:40',
                'updated_at' => '2026-01-22 10:27:40',
            ),
        ));
        
        
    }
}