<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UserFoldersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('user_folders')->delete();
        
        \DB::table('user_folders')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 1,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-12 08:00:28',
                'updated_at' => '2026-01-12 08:00:28',
            ),
            1 => 
            array (
                'id' => 11,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 5,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-12 15:53:22',
                'updated_at' => '2026-01-12 15:53:22',
            ),
            2 => 
            array (
                'id' => 12,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 9,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-12 16:03:19',
                'updated_at' => '2026-01-12 16:03:19',
            ),
            3 => 
            array (
                'id' => 13,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 8,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-12 16:04:00',
                'updated_at' => '2026-01-12 16:04:00',
            ),
            4 => 
            array (
                'id' => 14,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 11,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-12 16:04:27',
                'updated_at' => '2026-01-12 16:04:27',
            ),
            5 => 
            array (
                'id' => 15,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 12,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-12 16:04:51',
                'updated_at' => '2026-01-12 16:04:51',
            ),
            6 => 
            array (
                'id' => 16,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 13,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-12 16:05:15',
                'updated_at' => '2026-01-12 16:05:15',
            ),
            7 => 
            array (
                'id' => 17,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 14,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-12 16:05:32',
                'updated_at' => '2026-01-12 16:05:32',
            ),
            8 => 
            array (
                'id' => 18,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 15,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-12 16:05:48',
                'updated_at' => '2026-01-12 16:05:48',
            ),
            9 => 
            array (
                'id' => 19,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 16,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-12 16:06:04',
                'updated_at' => '2026-01-12 16:06:04',
            ),
            10 => 
            array (
                'id' => 20,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 17,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-12 16:06:22',
                'updated_at' => '2026-01-12 16:06:22',
            ),
            11 => 
            array (
                'id' => 21,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 6,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-13 09:32:22',
                'updated_at' => '2026-01-13 09:32:22',
            ),
            12 => 
            array (
                'id' => 22,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 19,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-13 09:34:14',
                'updated_at' => '2026-01-13 09:34:14',
            ),
            13 => 
            array (
                'id' => 24,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 20,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-13 09:40:37',
                'updated_at' => '2026-01-13 09:40:37',
            ),
            14 => 
            array (
                'id' => 25,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 21,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-13 09:42:17',
                'updated_at' => '2026-01-13 09:42:17',
            ),
            15 => 
            array (
                'id' => 26,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 22,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-13 09:46:26',
                'updated_at' => '2026-01-13 09:46:26',
            ),
            16 => 
            array (
                'id' => 27,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 24,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-13 09:47:49',
                'updated_at' => '2026-01-13 09:47:49',
            ),
            17 => 
            array (
                'id' => 28,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 26,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-13 09:51:32',
                'updated_at' => '2026-01-13 09:51:32',
            ),
            18 => 
            array (
                'id' => 29,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 27,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-13 09:52:29',
                'updated_at' => '2026-01-13 09:52:29',
            ),
            19 => 
            array (
                'id' => 30,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 37,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-14 13:33:29',
                'updated_at' => '2026-01-14 13:33:29',
            ),
            20 => 
            array (
                'id' => 31,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 7,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-14 13:33:32',
                'updated_at' => '2026-01-14 13:33:32',
            ),
            21 => 
            array (
                'id' => 32,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 29,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-14 13:34:20',
                'updated_at' => '2026-01-14 13:34:20',
            ),
            22 => 
            array (
                'id' => 33,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 28,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-14 13:35:23',
                'updated_at' => '2026-01-14 13:35:23',
            ),
            23 => 
            array (
                'id' => 34,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 30,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-14 13:36:11',
                'updated_at' => '2026-01-14 13:36:11',
            ),
            24 => 
            array (
                'id' => 35,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 32,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-14 13:37:07',
                'updated_at' => '2026-01-14 13:37:07',
            ),
            25 => 
            array (
                'id' => 36,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 31,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-14 13:38:24',
                'updated_at' => '2026-01-14 13:38:24',
            ),
            26 => 
            array (
                'id' => 37,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 33,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-14 13:39:37',
                'updated_at' => '2026-01-14 13:39:37',
            ),
            27 => 
            array (
                'id' => 38,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 36,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-14 13:47:50',
                'updated_at' => '2026-01-14 13:47:50',
            ),
            28 => 
            array (
                'id' => 39,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 38,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-14 13:48:26',
                'updated_at' => '2026-01-14 13:48:26',
            ),
            29 => 
            array (
                'id' => 40,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 35,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-14 13:50:26',
                'updated_at' => '2026-01-14 13:50:26',
            ),
            30 => 
            array (
                'id' => 41,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 39,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-19 13:39:13',
                'updated_at' => '2026-01-19 13:39:13',
            ),
            31 => 
            array (
                'id' => 42,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 40,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-19 13:43:26',
                'updated_at' => '2026-01-19 13:43:26',
            ),
            32 => 
            array (
                'id' => 44,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 41,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-19 13:45:37',
                'updated_at' => '2026-01-19 13:45:37',
            ),
            33 => 
            array (
                'id' => 46,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 42,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-19 13:55:33',
                'updated_at' => '2026-01-19 13:55:33',
            ),
            34 => 
            array (
                'id' => 50,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 48,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-19 14:13:31',
                'updated_at' => '2026-01-19 14:13:31',
            ),
            35 => 
            array (
                'id' => 51,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 49,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-19 14:18:50',
                'updated_at' => '2026-01-19 14:18:50',
            ),
            36 => 
            array (
                'id' => 52,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 50,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-19 14:20:55',
                'updated_at' => '2026-01-19 14:20:55',
            ),
            37 => 
            array (
                'id' => 53,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 10,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-19 14:22:27',
                'updated_at' => '2026-01-19 14:22:27',
            ),
            38 => 
            array (
                'id' => 54,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 51,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-19 14:29:19',
                'updated_at' => '2026-01-19 14:29:19',
            ),
            39 => 
            array (
                'id' => 55,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 52,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-19 14:33:33',
                'updated_at' => '2026-01-19 14:33:33',
            ),
            40 => 
            array (
                'id' => 56,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 53,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-19 14:35:51',
                'updated_at' => '2026-01-19 14:35:51',
            ),
            41 => 
            array (
                'id' => 57,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 54,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-19 14:37:50',
                'updated_at' => '2026-01-19 14:37:50',
            ),
            42 => 
            array (
                'id' => 58,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 55,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-19 14:40:31',
                'updated_at' => '2026-01-19 14:40:31',
            ),
            43 => 
            array (
                'id' => 59,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 56,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-19 14:58:29',
                'updated_at' => '2026-01-19 14:58:29',
            ),
            44 => 
            array (
                'id' => 60,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 57,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-19 16:12:04',
                'updated_at' => '2026-01-19 16:12:04',
            ),
            45 => 
            array (
                'id' => 61,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 58,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-19 16:19:27',
                'updated_at' => '2026-01-19 16:19:27',
            ),
            46 => 
            array (
                'id' => 62,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 59,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-19 16:28:37',
                'updated_at' => '2026-01-19 16:28:37',
            ),
            47 => 
            array (
                'id' => 64,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 61,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-20 13:35:10',
                'updated_at' => '2026-01-20 13:35:10',
            ),
            48 => 
            array (
                'id' => 66,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 62,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-20 13:38:22',
                'updated_at' => '2026-01-20 13:38:22',
            ),
            49 => 
            array (
                'id' => 67,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 63,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-20 13:46:37',
                'updated_at' => '2026-01-20 13:46:37',
            ),
            50 => 
            array (
                'id' => 69,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 65,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-20 13:54:21',
                'updated_at' => '2026-01-20 13:54:21',
            ),
            51 => 
            array (
                'id' => 70,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 67,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-20 15:32:51',
                'updated_at' => '2026-01-20 15:32:51',
            ),
            52 => 
            array (
                'id' => 72,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 69,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-20 15:56:14',
                'updated_at' => '2026-01-20 15:56:14',
            ),
            53 => 
            array (
                'id' => 74,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 70,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-20 15:59:51',
                'updated_at' => '2026-01-20 15:59:51',
            ),
            54 => 
            array (
                'id' => 76,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 71,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-20 16:07:13',
                'updated_at' => '2026-01-20 16:07:13',
            ),
            55 => 
            array (
                'id' => 78,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 18,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-20 16:08:27',
                'updated_at' => '2026-01-20 16:08:27',
            ),
            56 => 
            array (
                'id' => 80,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 73,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-20 16:14:37',
                'updated_at' => '2026-01-20 16:14:37',
            ),
            57 => 
            array (
                'id' => 82,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 74,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-21 08:15:57',
                'updated_at' => '2026-01-21 08:15:57',
            ),
            58 => 
            array (
                'id' => 84,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 75,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-21 08:20:06',
                'updated_at' => '2026-01-21 08:20:06',
            ),
            59 => 
            array (
                'id' => 86,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 76,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-21 08:23:08',
                'updated_at' => '2026-01-21 08:23:08',
            ),
            60 => 
            array (
                'id' => 88,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 77,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-21 08:26:49',
                'updated_at' => '2026-01-21 08:26:49',
            ),
            61 => 
            array (
                'id' => 89,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 78,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-21 08:31:53',
                'updated_at' => '2026-01-21 08:31:53',
            ),
            62 => 
            array (
                'id' => 90,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 81,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-21 08:39:53',
                'updated_at' => '2026-01-21 08:39:53',
            ),
            63 => 
            array (
                'id' => 92,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 82,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-21 08:43:03',
                'updated_at' => '2026-01-21 08:43:03',
            ),
            64 => 
            array (
                'id' => 94,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 83,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-21 08:47:12',
                'updated_at' => '2026-01-21 08:47:12',
            ),
            65 => 
            array (
                'id' => 96,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 84,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-21 08:49:19',
                'updated_at' => '2026-01-21 08:49:19',
            ),
            66 => 
            array (
                'id' => 98,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 85,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-21 08:55:14',
                'updated_at' => '2026-01-21 08:55:14',
            ),
            67 => 
            array (
                'id' => 99,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 86,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-21 09:11:01',
                'updated_at' => '2026-01-21 09:11:01',
            ),
            68 => 
            array (
                'id' => 100,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 87,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-21 09:18:41',
                'updated_at' => '2026-01-21 09:18:41',
            ),
            69 => 
            array (
                'id' => 102,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 88,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-21 09:27:02',
                'updated_at' => '2026-01-21 09:27:02',
            ),
            70 => 
            array (
                'id' => 103,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 89,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-21 09:31:43',
                'updated_at' => '2026-01-21 09:31:43',
            ),
            71 => 
            array (
                'id' => 104,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 90,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-21 09:36:03',
                'updated_at' => '2026-01-21 09:36:03',
            ),
            72 => 
            array (
                'id' => 106,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 92,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-21 10:00:07',
                'updated_at' => '2026-01-21 10:00:07',
            ),
            73 => 
            array (
                'id' => 108,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 93,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-21 10:09:03',
                'updated_at' => '2026-01-21 10:09:03',
            ),
            74 => 
            array (
                'id' => 110,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 94,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-21 10:14:46',
                'updated_at' => '2026-01-21 10:14:46',
            ),
            75 => 
            array (
                'id' => 112,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 91,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-21 16:52:24',
                'updated_at' => '2026-01-21 16:52:24',
            ),
            76 => 
            array (
                'id' => 113,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 113,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-21 21:40:42',
                'updated_at' => '2026-01-21 21:40:42',
            ),
            77 => 
            array (
                'id' => 115,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 111,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-21 21:42:58',
                'updated_at' => '2026-01-21 21:42:58',
            ),
            78 => 
            array (
                'id' => 117,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 110,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-21 21:45:34',
                'updated_at' => '2026-01-21 21:45:34',
            ),
            79 => 
            array (
                'id' => 119,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 109,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-21 21:54:15',
                'updated_at' => '2026-01-21 21:54:15',
            ),
            80 => 
            array (
                'id' => 120,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 108,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-21 21:56:38',
                'updated_at' => '2026-01-21 21:56:38',
            ),
            81 => 
            array (
                'id' => 121,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 105,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-21 21:59:32',
                'updated_at' => '2026-01-21 21:59:32',
            ),
            82 => 
            array (
                'id' => 122,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 104,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-21 22:00:14',
                'updated_at' => '2026-01-21 22:00:14',
            ),
            83 => 
            array (
                'id' => 124,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 103,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-21 22:01:04',
                'updated_at' => '2026-01-21 22:01:04',
            ),
            84 => 
            array (
                'id' => 126,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 102,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-21 22:02:55',
                'updated_at' => '2026-01-21 22:02:55',
            ),
            85 => 
            array (
                'id' => 130,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 100,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-21 22:04:39',
                'updated_at' => '2026-01-21 22:04:39',
            ),
            86 => 
            array (
                'id' => 132,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 98,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-21 22:05:16',
                'updated_at' => '2026-01-21 22:05:16',
            ),
            87 => 
            array (
                'id' => 133,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 96,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-21 22:10:55',
                'updated_at' => '2026-01-21 22:10:55',
            ),
            88 => 
            array (
                'id' => 135,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 2,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-21 22:18:07',
                'updated_at' => '2026-01-21 22:18:07',
            ),
            89 => 
            array (
                'id' => 137,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 3,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-21 22:20:25',
                'updated_at' => '2026-01-21 22:20:25',
            ),
            90 => 
            array (
                'id' => 139,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 4,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-21 22:21:44',
                'updated_at' => '2026-01-21 22:21:44',
            ),
            91 => 
            array (
                'id' => 141,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 23,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-21 22:28:11',
                'updated_at' => '2026-01-21 22:28:11',
            ),
            92 => 
            array (
                'id' => 145,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 25,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-21 22:30:14',
                'updated_at' => '2026-01-21 22:30:14',
            ),
            93 => 
            array (
                'id' => 147,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 34,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-21 22:33:08',
                'updated_at' => '2026-01-21 22:33:08',
            ),
            94 => 
            array (
                'id' => 149,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 43,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-21 22:34:32',
                'updated_at' => '2026-01-21 22:34:32',
            ),
            95 => 
            array (
                'id' => 150,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 44,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-21 22:35:31',
                'updated_at' => '2026-01-21 22:35:31',
            ),
            96 => 
            array (
                'id' => 151,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 45,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-21 22:36:10',
                'updated_at' => '2026-01-21 22:36:10',
            ),
            97 => 
            array (
                'id' => 153,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 106,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-22 08:31:05',
                'updated_at' => '2026-01-22 08:31:05',
            ),
            98 => 
            array (
                'id' => 154,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 107,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-22 08:31:31',
                'updated_at' => '2026-01-22 08:31:31',
            ),
            99 => 
            array (
                'id' => 156,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 116,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-22 08:54:45',
                'updated_at' => '2026-01-22 08:54:45',
            ),
            100 => 
            array (
                'id' => 157,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 114,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-22 09:00:51',
                'updated_at' => '2026-01-22 09:00:51',
            ),
            101 => 
            array (
                'id' => 158,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 117,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-22 09:06:02',
                'updated_at' => '2026-01-22 09:06:02',
            ),
            102 => 
            array (
                'id' => 159,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 115,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-22 09:18:37',
                'updated_at' => '2026-01-22 09:18:37',
            ),
            103 => 
            array (
                'id' => 160,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 118,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-22 09:31:30',
                'updated_at' => '2026-01-22 09:31:30',
            ),
            104 => 
            array (
                'id' => 163,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 119,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-22 09:32:07',
                'updated_at' => '2026-01-22 09:32:07',
            ),
            105 => 
            array (
                'id' => 165,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 120,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-22 09:41:02',
                'updated_at' => '2026-01-22 09:41:02',
            ),
            106 => 
            array (
                'id' => 166,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 121,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-22 10:09:05',
                'updated_at' => '2026-01-22 10:09:05',
            ),
            107 => 
            array (
                'id' => 168,
                'name' => 'Reference',
                'description' => NULL,
                'is_public' => 0,
                'is_protected' => 0,
                'user_id' => 122,
                'opened_at' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2026-01-22 10:35:22',
                'updated_at' => '2026-01-22 10:35:22',
            ),
        ));
        
        
    }
}